[package]
name = "check-project"
version = "0.1.0"
edition = "2018"
authors = ["Phil <PhilboBaggins@users.noreply.github.com>"]

[dependencies]
clap = "2.32.0"
cargo_toml = "0.3.0"
rust-ini = "0.12.2"
